In [1]:
from Univariate import Univariate
import pandas as pd

In [2]:
dataset = pd.read_csv("Placement.csv")

In [3]:
dataset

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary
0,1,M,67.00,Others,91.00,Others,Commerce,58.00,Sci&Tech,No,55.0,Mkt&HR,58.80,Placed,270000.0
1,2,M,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,Yes,86.5,Mkt&Fin,66.28,Placed,200000.0
2,3,M,65.00,Central,68.00,Central,Arts,64.00,Comm&Mgmt,No,75.0,Mkt&Fin,57.80,Placed,250000.0
3,4,M,56.00,Central,52.00,Central,Science,52.00,Sci&Tech,No,66.0,Mkt&HR,59.43,Not Placed,NaN
4,5,M,85.80,Central,73.60,Central,Commerce,73.30,Comm&Mgmt,No,96.8,Mkt&Fin,55.50,Placed,425000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,211,M,80.60,Others,82.00,Others,Commerce,77.60,Comm&Mgmt,No,91.0,Mkt&Fin,74.49,Placed,400000.0
211,212,M,58.00,Others,60.00,Others,Science,72.00,Sci&Tech,No,74.0,Mkt&Fin,53.62,Placed,275000.0
212,213,M,67.00,Others,67.00,Others,Commerce,73.00,Comm&Mgmt,Yes,59.0,Mkt&Fin,69.72,Placed,295000.0
213,214,F,74.00,Others,66.00,Others,Commerce,58.00,Comm&Mgmt,No,70.0,Mkt&HR,60.23,Placed,204000.0
214,215,M,62.00,Central,58.00,Others,Science,53.00,Comm&Mgmt,No,89.0,Mkt&HR,60.22,Not Placed,NaN

In [4]:
quan,qual=Univariate.quanQual(dataset)

In [5]:
quan

['sl_no', 'ssc_p', 'hsc_p', 'degree_p', 'etest_p', 'mba_p', 'salary']

In [6]:
qual

['gender',
 'ssc_b',
 'hsc_b',
 'hsc_s',
 'degree_t',
 'workex',
 'specialisation',
 'status']

In [7]:
dataset

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary
0,1,M,67.00,Others,91.00,Others,Commerce,58.00,Sci&Tech,No,55.0,Mkt&HR,58.80,Placed,270000.0
1,2,M,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,Yes,86.5,Mkt&Fin,66.28,Placed,200000.0
2,3,M,65.00,Central,68.00,Central,Arts,64.00,Comm&Mgmt,No,75.0,Mkt&Fin,57.80,Placed,250000.0
3,4,M,56.00,Central,52.00,Central,Science,52.00,Sci&Tech,No,66.0,Mkt&HR,59.43,Not Placed,NaN
4,5,M,85.80,Central,73.60,Central,Commerce,73.30,Comm&Mgmt,No,96.8,Mkt&Fin,55.50,Placed,425000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,211,M,80.60,Others,82.00,Others,Commerce,77.60,Comm&Mgmt,No,91.0,Mkt&Fin,74.49,Placed,400000.0
211,212,M,58.00,Others,60.00,Others,Science,72.00,Sci&Tech,No,74.0,Mkt&Fin,53.62,Placed,275000.0
212,213,M,67.00,Others,67.00,Others,Commerce,73.00,Comm&Mgmt,Yes,59.0,Mkt&Fin,69.72,Placed,295000.0
213,214,F,74.00,Others,66.00,Others,Commerce,58.00,Comm&Mgmt,No,70.0,Mkt&HR,60.23,Placed,204000.0
214,215,M,62.00,Central,58.00,Others,Science,53.00,Comm&Mgmt,No,89.0,Mkt&HR,60.22,Not Placed,NaN

# Central tendency

In [8]:
print(dataset["ssc_p"].mean())

67.30339534883721

In [9]:
print(dataset["ssc_p"].median())

67.0

In [10]:
print(dataset["ssc_p"].mode()[0])

62.0

In [11]:
dataset.describe()

,sl_no,ssc_p,hsc_p,degree_p,etest_p,mba_p,salary
count,215.000000,215.000000,215.000000,215.000000,215.000000,215.000000,148.000000
mean,108.000000,67.303395,66.333163,66.370186,72.100558,62.278186,288655.405405
std,62.209324,10.827205,10.897509,7.358743,13.275956,5.833385,93457.452420
min,1.000000,40.890000,37.000000,50.000000,50.000000,51.210000,200000.000000
25%,54.500000,60.600000,60.900000,61.000000,60.000000,57.945000,240000.000000
50%,108.000000,67.000000,65.000000,66.000000,71.000000,62.000000,265000.000000
75%,161.500000,75.700000,73.000000,72.000000,83.500000,66.255000,300000.000000
max,215.000000,89.400000,97.700000,91.000000,98.000000,77.890000,940000.000000

In [12]:
descriptive = pd.DataFrame()

In [13]:
descriptive = pd.DataFrame(index=["Mean", "Median", "Mode"],columns=quan)

In [14]:
descriptive

       sl_no ssc_p hsc_p degree_p etest_p mba_p salary
Mean     NaN   NaN   NaN      NaN     NaN   NaN    NaN
Median   NaN   NaN   NaN      NaN     NaN   NaN    NaN
Mode     NaN   NaN   NaN      NaN     NaN   NaN    NaN

In [15]:
descriptive.loc["Median", "hsc_p"]=0
descriptive

       sl_no ssc_p hsc_p degree_p etest_p mba_p salary
Mean     NaN   NaN   NaN      NaN     NaN   NaN    NaN
Median   NaN   NaN     0      NaN     NaN   NaN    NaN
Mode     NaN   NaN   NaN      NaN     NaN   NaN    NaN

In [16]:
descriptive = pd.DataFrame(index=["Mean", "Median", "Mode"],columns=quan)
for ColumnName in quan:
    descriptive.loc["Mean", ColumnName]=dataset[ColumnName].mean()

In [17]:
descriptive

,sl_no,ssc_p,hsc_p,degree_p,etest_p,mba_p,salary
Mean,108.0,67.303395,66.333163,66.370186,72.100558,62.278186,288655.405405
Median,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Mode,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
descriptive = pd.DataFrame(index=["Mean", "Median", "Mode"],columns=quan)
for ColumnName in quan:
    descriptive.loc["Mean", ColumnName]=dataset[ColumnName].mean()
    descriptive.loc["Median", ColumnName]=dataset[ColumnName].median()

In [19]:
descriptive

,sl_no,ssc_p,hsc_p,degree_p,etest_p,mba_p,salary
Mean,108.0,67.303395,66.333163,66.370186,72.100558,62.278186,288655.405405
Median,108.0,67.0,65.0,66.0,71.0,62.0,265000.0
Mode,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [20]:
descriptive = pd.DataFrame(index=["Mean", "Median", "Mode"],columns=quan)
for ColumnName in quan:
     descriptive.loc["Mean", ColumnName]=dataset[ColumnName].mean()
     descriptive.loc["Median", ColumnName]=dataset[ColumnName].median()
     descriptive.loc["Mode", ColumnName]=dataset[ColumnName].mode()[0]

In [21]:
descriptive

,sl_no,ssc_p,hsc_p,degree_p,etest_p,mba_p,salary
Mean,108.0,67.303395,66.333163,66.370186,72.100558,62.278186,288655.405405
Median,108.0,67.0,65.0,66.0,71.0,62.0,265000.0
Mode,1,62.0,63.0,65.0,60.0,56.7,300000.0

# Percentile

In [22]:
import numpy as np

In [23]:
print(np.percentile(dataset["ssc_p"],50))

67.0

In [24]:
descriptive = pd.DataFrame(index=["Mean", "Median", "Mode","Q1:25%", "Q2:50%", "Q3:75%", "Q4:100%"],columns=quan)
for ColumnName in quan:
    descriptive.loc["Mean", ColumnName]=dataset[ColumnName].mean()
    descriptive.loc["Median", ColumnName]=dataset[ColumnName].median()
    descriptive.loc["Mode", ColumnName]=dataset[ColumnName].mode()[0]
    descriptive.loc["Q1:25%", ColumnName]=dataset.describe()[ColumnName]["25%"]
    descriptive.loc["Q2:50%", ColumnName]=dataset.describe()[ColumnName]["50%"]
    descriptive.loc["Q3:75%", ColumnName]=dataset.describe()[ColumnName]["75%"]
    descriptive.loc["Q4:100%", ColumnName]=dataset.describe()[ColumnName]["max"]

In [25]:
descriptive

,sl_no,ssc_p,hsc_p,degree_p,etest_p,mba_p,salary
Mean,108.0,67.303395,66.333163,66.370186,72.100558,62.278186,288655.405405
Median,108.0,67.0,65.0,66.0,71.0,62.0,265000.0
Mode,1,62.0,63.0,65.0,60.0,56.7,300000.0
Q1:25%,54.5,60.6,60.9,61.0,60.0,57.945,240000.0
Q2:50%,108.0,67.0,65.0,66.0,71.0,62.0,265000.0
Q3:75%,161.5,75.7,73.0,72.0,83.5,66.255,300000.0
Q4:100%,215.0,89.4,97.7,91.0,98.0,77.89,940000.0

# IQR_interquartile range

In [26]:
descriptive = pd.DataFrame(index=["Mean", "Median", "Mode","Q1:25%", "Q2:50%", "Q3:75%", "Q4:100%","IQR",
                                 "1.5rule", "Lesser", "Greater", "Min", "Max"],columns=quan)
for ColumnName in quan:
    descriptive.loc["Mean", ColumnName]=dataset[ColumnName].mean()
    descriptive.loc["Median", ColumnName]=dataset[ColumnName].median()
    descriptive.loc["Mode", ColumnName]=dataset[ColumnName].mode()[0]
    descriptive.loc["Q1:25%", ColumnName]=dataset.describe()[ColumnName]["25%"]
    descriptive.loc["Q2:50%", ColumnName]=dataset.describe()[ColumnName]["50%"]
    descriptive.loc["Q3:75%", ColumnName]=dataset.describe()[ColumnName]["75%"]
    descriptive.loc["Q4:100%", ColumnName]=dataset.describe()[ColumnName]["max"]
    descriptive.loc["IQR", ColumnName] = descriptive.loc["Q3:75%", ColumnName]-descriptive.loc["Q1:25%", ColumnName]
    descriptive.loc["1.5rule", ColumnName] = 1.5 * descriptive.loc["IQR", ColumnName]
    descriptive.loc["Lesser", ColumnName] = descriptive.loc["Q1:25%", ColumnName] -  descriptive.loc["1.5rule", ColumnName]
    descriptive.loc["Greater", ColumnName] =  descriptive.loc["Q3:75%", ColumnName] + descriptive.loc["1.5rule", ColumnName]
    descriptive.loc["Min", ColumnName] = dataset[ColumnName].min()
    descriptive.loc["Max", ColumnName] = dataset[ColumnName].max()

In [27]:
descriptive

,sl_no,ssc_p,hsc_p,degree_p,etest_p,mba_p,salary
Mean,108.0,67.303395,66.333163,66.370186,72.100558,62.278186,288655.405405
Median,108.0,67.0,65.0,66.0,71.0,62.0,265000.0
Mode,1,62.0,63.0,65.0,60.0,56.7,300000.0
Q1:25%,54.5,60.6,60.9,61.0,60.0,57.945,240000.0
Q2:50%,108.0,67.0,65.0,66.0,71.0,62.0,265000.0
Q3:75%,161.5,75.7,73.0,72.0,83.5,66.255,300000.0
Q4:100%,215.0,89.4,97.7,91.0,98.0,77.89,940000.0
IQR,107.0,15.1,12.1,11.0,23.5,8.31,60000.0
1.5rule,160.5,22.65,18.15,16.5,35.25,12.465,90000.0
Lesser,-106.0,37.95,42.75,44.5,24.75,45.48,150000.0
Greater,322.0,98.35,91.15,88.5,118.75,78.72,390000.0
Min,1,40.89,37.0,50.0,50.0,51.21,200000.0
Max,215,89.4,97.7,91.0,98.0,77.89,940000.0

In [28]:
descriptive[ColumnName][ "Min"] < descriptive[ColumnName][ "Lesser"]

np.False_

In [29]:
lesser = []
greater = []

for ColumnName in quan:
    if(descriptive[ColumnName]["Min"] < descriptive[ColumnName]["Lesser"]):
        lesser.append(ColumnName)
    if(descriptive[ColumnName]["Max"] > descriptive[ColumnName]["Greater"]):
        greater.append(ColumnName)

In [30]:
lesser

['hsc_p']

In [31]:
greater

['hsc_p', 'degree_p', 'salary']

In [32]:
for ColumnName in lesser:
    dataset.loc[dataset[ColumnName]<descriptive[ColumnName]["Lesser"],ColumnName] = descriptive[ColumnName]["Lesser"]
for ColumnName in greater:
    dataset.loc[dataset[ColumnName]>descriptive[ColumnName]["Greater"], ColumnName] = descriptive[ColumnName]["Greater"]

In [33]:
descriptive = pd.DataFrame(index=["Mean", "Median", "Mode","Q1:25%", "Q2:50%", "Q3:75%", "Q4:100%","IQR",
                                 "1.5rule", "Lesser", "Greater", "Min", "Max"],columns=quan)
for ColumnName in quan:
    descriptive.loc["Mean", ColumnName]=dataset[ColumnName].mean()
    descriptive.loc["Median", ColumnName]=dataset[ColumnName].median()
    descriptive.loc["Mode", ColumnName]=dataset[ColumnName].mode()[0]
    descriptive.loc["Q1:25%", ColumnName]=dataset.describe()[ColumnName]["25%"]
    descriptive.loc["Q2:50%", ColumnName]=dataset.describe()[ColumnName]["50%"]
    descriptive.loc["Q3:75%", ColumnName]=dataset.describe()[ColumnName]["75%"]
    descriptive.loc["Q4:100%", ColumnName]=dataset.describe()[ColumnName]["max"]
    descriptive.loc["IQR", ColumnName] = descriptive.loc["Q3:75%", ColumnName]-descriptive.loc["Q1:25%", ColumnName]
    descriptive.loc["1.5rule", ColumnName] = 1.5 * descriptive.loc["IQR", ColumnName]
    descriptive.loc["Lesser", ColumnName] = descriptive.loc["Q1:25%", ColumnName] -  descriptive.loc["1.5rule", ColumnName]
    descriptive.loc["Greater", ColumnName] =  descriptive.loc["Q3:75%", ColumnName] + descriptive.loc["1.5rule", ColumnName]
    descriptive.loc["Min", ColumnName] = dataset[ColumnName].min()
    descriptive.loc["Max", ColumnName] = dataset[ColumnName].max()

In [34]:
descriptive

,sl_no,ssc_p,hsc_p,degree_p,etest_p,mba_p,salary
Mean,108.0,67.303395,66.334744,66.358558,72.100558,62.278186,277648.648649
Median,108.0,67.0,65.0,66.0,71.0,62.0,265000.0
Mode,1,62.0,63.0,65.0,60.0,56.7,300000.0
Q1:25%,54.5,60.6,60.9,61.0,60.0,57.945,240000.0
Q2:50%,108.0,67.0,65.0,66.0,71.0,62.0,265000.0
Q3:75%,161.5,75.7,73.0,72.0,83.5,66.255,300000.0
Q4:100%,215.0,89.4,91.15,88.5,98.0,77.89,390000.0
IQR,107.0,15.1,12.1,11.0,23.5,8.31,60000.0
1.5rule,160.5,22.65,18.15,16.5,35.25,12.465,90000.0
Lesser,-106.0,37.95,42.75,44.5,24.75,45.48,150000.0
Greater,322.0,98.35,91.15,88.5,118.75,78.72,390000.0
Min,1,40.89,42.75,50.0,50.0,51.21,200000.0
Max,215,89.4,91.15,88.5,98.0,77.89,390000.0

In [35]:
lesser = []
greater = []

for ColumnName in quan:
    if(descriptive[ColumnName]["Min"] < descriptive[ColumnName]["Lesser"]):
        lesser.append(ColumnName)
    if(descriptive[ColumnName]["Max"] > descriptive[ColumnName]["Greater"]):
        greater.append(ColumnName)

In [36]:
lesser

[]

In [37]:
greater

[]

In [38]:
dataset["ssc_p"].value_counts()

ssc_p
62.00    11
63.00    10
67.00     9
73.00     9
52.00     9
         ..
55.68     1
41.00     1
83.33     1
43.00     1
80.60     1
Name: count, Length: 103, dtype: int64

In [39]:
freqtable = pd.DataFrame(columns = ["Unique_Values", "Frequency", "Relative_Frequency", "Cumsum"])

In [40]:
freqtable

Empty DataFrame
Columns: [Unique_Values, Frequency, Relative_Frequency, Cumsum]
Index: []

In [41]:
freqtable["Unique_Values"] = dataset["ssc_p"].value_counts().index

In [42]:
freqtable

     Unique_Values Frequency Relative_Frequency Cumsum
0            62.00       NaN                NaN    NaN
1            63.00       NaN                NaN    NaN
2            67.00       NaN                NaN    NaN
3            73.00       NaN                NaN    NaN
4            52.00       NaN                NaN    NaN
..             ...       ...                ...    ...
98           55.68       NaN                NaN    NaN
99           41.00       NaN                NaN    NaN
100          83.33       NaN                NaN    NaN
101          43.00       NaN                NaN    NaN
102          80.60       NaN                NaN    NaN

[103 rows x 4 columns]

In [43]:
freqtable["Unique_Values"] = dataset["ssc_p"].value_counts().index
freqtable["Frequency"] = dataset["ssc_p"].value_counts().values

In [44]:
freqtable

     Unique_Values  Frequency Relative_Frequency Cumsum
0            62.00         11                NaN    NaN
1            63.00         10                NaN    NaN
2            67.00          9                NaN    NaN
3            73.00          9                NaN    NaN
4            52.00          9                NaN    NaN
..             ...        ...                ...    ...
98           55.68          1                NaN    NaN
99           41.00          1                NaN    NaN
100          83.33          1                NaN    NaN
101          43.00          1                NaN    NaN
102          80.60          1                NaN    NaN

[103 rows x 4 columns]

In [45]:
freqtable["Unique_Values"] = dataset["ssc_p"].value_counts().index
freqtable["Frequency"] = dataset["ssc_p"].value_counts().values
freqtable["Relative_Frequency"] = freqtable["Frequency"]/ 103

In [46]:
freqtable

     Unique_Values  Frequency  Relative_Frequency Cumsum
0            62.00         11            0.106796    NaN
1            63.00         10            0.097087    NaN
2            67.00          9            0.087379    NaN
3            73.00          9            0.087379    NaN
4            52.00          9            0.087379    NaN
..             ...        ...                 ...    ...
98           55.68          1            0.009709    NaN
99           41.00          1            0.009709    NaN
100          83.33          1            0.009709    NaN
101          43.00          1            0.009709    NaN
102          80.60          1            0.009709    NaN

[103 rows x 4 columns]

In [47]:
freqtable["Unique_Values"] = dataset["ssc_p"].value_counts().index
freqtable["Frequency"] = dataset["ssc_p"].value_counts().values
freqtable["Relative_Frequency"] = freqtable["Frequency"]/ 103
freqtable["Cumsum"] = freqtable["Relative_Frequency"].cumsum()

In [48]:
freqtable

     Unique_Values  Frequency  Relative_Frequency    Cumsum
0            62.00         11            0.106796  0.106796
1            63.00         10            0.097087  0.203883
2            67.00          9            0.087379  0.291262
3            73.00          9            0.087379  0.378641
4            52.00          9            0.087379  0.466019
..             ...        ...                 ...       ...
98           55.68          1            0.009709  2.048544
99           41.00          1            0.009709  2.058252
100          83.33          1            0.009709  2.067961
101          43.00          1            0.009709  2.077670
102          80.60          1            0.009709  2.087379

[103 rows x 4 columns]

In [60]:
def Univariate(dataset, quan):
    freqtable = pd.DataFrame(columns = ["Unique_Values", "Frequency", "Relative_Frequency", "Cumsum"])
    freqtable["Unique_Values"] = dataset["ssc_p"].value_counts().index
    freqtable["Frequency"] = dataset["ssc_p"].value_counts().values
    freqtable["Relative_Frequency"] = freqtable["Frequency"]/ 103
    freqtable["Cumsum"] = freqtable["Relative_Frequency"].cumsum()
    return freqtable

In [61]:
Univariate(dataset, quan)

     Unique_Values  Frequency  Relative_Frequency    Cumsum
0            62.00         11            0.106796  0.106796
1            63.00         10            0.097087  0.203883
2            67.00          9            0.087379  0.291262
3            73.00          9            0.087379  0.378641
4            52.00          9            0.087379  0.466019
..             ...        ...                 ...       ...
98           55.68          1            0.009709  2.048544
99           41.00          1            0.009709  2.058252
100          83.33          1            0.009709  2.067961
101          43.00          1            0.009709  2.077670
102          80.60          1            0.009709  2.087379

[103 rows x 4 columns]

In [62]:
freqtable("salary", dataset)

    Unique_Values  Frequency  Relative_Frequency    Cumsum
0        300000.0         22            0.213592  0.213592
1        250000.0         18            0.174757  0.388350
2        390000.0         15            0.145631  0.533981
3        240000.0         15            0.145631  0.679612
4        260000.0          7            0.067961  0.747573
5        200000.0          6            0.058252  0.805825
6        265000.0          6            0.058252  0.864078
7        360000.0          6            0.058252  0.922330
8        220000.0          5            0.048544  0.970874
9        275000.0          5            0.048544  1.019417
10       270000.0          4            0.038835  1.058252
11       210000.0          4            0.038835  1.097087
12       350000.0          3            0.029126  1.126214
13       216000.0          3            0.029126  1.155340
14       252000.0          2            0.019417  1.174757
15       218000.0          2            0.019417  1.194175
16       236000.0          2            0.019417  1.213592
17       204000.0          2            0.019417  1.233010
18       230000.0          2            0.019417  1.252427
19       280000.0          2            0.019417  1.271845
20       276000.0          2            0.019417  1.291262
21       231000.0          1            0.009709  1.300971
22       278000.0          1            0.009709  1.310680
23       320000.0          1            0.009709  1.320388
24       287000.0          1            0.009709  1.330097
25       268000.0          1            0.009709  1.339806
26       336000.0          1            0.009709  1.349515
27       380000.0          1            0.009709  1.359223
28       225000.0          1            0.009709  1.368932
29       233000.0          1            0.009709  1.378641
30       340000.0          1            0.009709  1.388350
31       255000.0          1            0.009709  1.398058
32       285000.0          1            0.009709  1.407767
33       290000.0          1            0.009709  1.417476
34       264000.0          1            0.009709  1.427184
35       295000.0          1            0.009709  1.436893

In [58]:
def Univariate(dataset, quan):
    descriptive = pd.DataFrame(index=["Mean", "Median", "Mode","Q1:25%", "Q2:50%", "Q3:75%", "Q4:100%","IQR",
                                 "1.5rule", "Lesser", "Greater", "Min", "Max"],columns=quan)
    for ColumnName in quan:
        descriptive.loc["Mean", ColumnName]=dataset[ColumnName].mean()
        descriptive.loc["Median", ColumnName]=dataset[ColumnName].median()
        descriptive.loc["Mode", ColumnName]=dataset[ColumnName].mode()[0]
        descriptive.loc["Q1:25%", ColumnName]=dataset.describe()[ColumnName]["25%"]
        descriptive.loc["Q2:50%", ColumnName]=dataset.describe()[ColumnName]["50%"]
        descriptive.loc["Q3:75%", ColumnName]=dataset.describe()[ColumnName]["75%"]
        descriptive.loc["Q4:100%", ColumnName]=dataset.describe()[ColumnName]["max"]
        descriptive.loc["IQR", ColumnName] = descriptive.loc["Q3:75%", ColumnName]-descriptive.loc["Q1:25%", ColumnName]
        descriptive.loc["1.5rule", ColumnName] = 1.5 * descriptive.loc["IQR", ColumnName]
        descriptive.loc["Lesser", ColumnName] = descriptive.loc["Q1:25%", ColumnName] -  descriptive.loc["1.5rule", ColumnName]
        descriptive.loc["Greater", ColumnName] =  descriptive.loc["Q3:75%", ColumnName] + descriptive.loc["1.5rule", ColumnName]
        descriptive.loc["Min", ColumnName] = dataset[ColumnName].min()
        descriptive.loc["Max", ColumnName] = dataset[ColumnName].max()
    return descriptive

In [59]:
Univariate(dataset, quan)

,sl_no,ssc_p,hsc_p,degree_p,etest_p,mba_p,salary
Mean,108.0,67.303395,66.334744,66.358558,72.100558,62.278186,277648.648649
Median,108.0,67.0,65.0,66.0,71.0,62.0,265000.0
Mode,1,62.0,63.0,65.0,60.0,56.7,300000.0
Q1:25%,54.5,60.6,60.9,61.0,60.0,57.945,240000.0
Q2:50%,108.0,67.0,65.0,66.0,71.0,62.0,265000.0
Q3:75%,161.5,75.7,73.0,72.0,83.5,66.255,300000.0
Q4:100%,215.0,89.4,91.15,88.5,98.0,77.89,390000.0
IQR,107.0,15.1,12.1,11.0,23.5,8.31,60000.0
1.5rule,160.5,22.65,18.15,16.5,35.25,12.465,90000.0
Lesser,-106.0,37.95,42.75,44.5,24.75,45.48,150000.0
Greater,322.0,98.35,91.15,88.5,118.75,78.72,390000.0
Min,1,40.89,42.75,50.0,50.0,51.21,200000.0
Max,215,89.4,91.15,88.5,98.0,77.89,390000.0